name: photo_stuffing
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  permission_handler: ^11.3.1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  image: ^4.1.7
  flutter_image_compress: ^2.2.0
  encrypt: ^5.0.3
  light: ^4.1.0
  flutter_windowmanager_plus: ^1.0.1
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true